"""add founder_profile table

Revision ID: 552fc109d89d
Revises: 5710a17a739b
Create Date: 2026-06-25 21:22:48.612550
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '552fc109d89d'
down_revision: str | None = '5710a17a739b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('founder_profile',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('current_country', sa.String(length=200), nullable=False),
    sa.Column('active_markets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('technical_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('business_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_business_type', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tools_available', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active_projects', sa.Text(), nullable=False),
    sa.Column('budget_range', sa.String(length=50), nullable=False),
    sa.Column('avoid', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('founder_profile')
    # ### end Alembic commands ###
