"""initial: opportunities and daily_reports

Revision ID: 5710a17a739b
Revises: 
Create Date: 2026-06-25 18:50:30.847541
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5710a17a739b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('total_analyzed', sa.Integer(), nullable=False),
    sa.Column('promising_count', sa.Integer(), nullable=False),
    sa.Column('excellent_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_reports_report_date'), 'daily_reports', ['report_date'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('topic_origin', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'DISCARDED', name='opportunity_status'), nullable=False),
    sa.Column('discard_reason', sa.Text(), nullable=True),
    sa.Column('discarded_by', sa.String(length=100), nullable=True),
    sa.Column('trend_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('problem_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('competitor_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_opportunity_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('compatibility_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('monetization_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('project_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('devils_advocate_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score_total', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_opportunities_created_at', 'opportunities', ['created_at'], unique=False)
    op.create_index('ix_opportunities_score_total', 'opportunities', ['score_total'], unique=False)
    op.create_index('ix_opportunities_status', 'opportunities', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_opportunities_status', table_name='opportunities')
    op.drop_index('ix_opportunities_score_total', table_name='opportunities')
    op.drop_index('ix_opportunities_created_at', table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_daily_reports_report_date'), table_name='daily_reports')
    op.drop_table('daily_reports')
    # ### end Alembic commands ###
